const actionTypes = {
  ALL_products: 'ALL_products',
  SINGLE_product: 'SINGLE_product',
  SIGN_UP: 'SIGN_UP',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
};

export default actionTypes;
