const actionTypes = {
  ALL_PRODUCTS: 'ALL_products',
  SINGLE_PRODUCT: 'SINGLE_product',
  SIGN_UP: 'SIGN_UP',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  MY_PRODUCTS: 'MY_PRODUCTS',
  NEW_PRODUCT: 'NEW_PRODUCT',
  NEW_PRODUCT_FAIL: 'NEW_PRODUCT_FAIL',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',
};

export default actionTypes;
